version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-mangatracker
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: MangaTracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
